### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by zq2017** [appurwar/Contextual-Bandit-News-Article-Recommendation#1]
Dear Apoorv Purwar,
        When I was running the program, there were something wrong that looks like the following,  can you help me find out the reason?
Traceback (most recent call last):
  File "F:/Contextual-Bandit-News-Article-Recommendation-master/newsArticleRecommendation.py", line 207, in <module>
    CTR3 = linUCB(data, -1)
  File "F:/Contextual-Bandit-News-Article-Recommendation-master/newsArticleRecommendation.py", line 95, in linUCB
    denom = 0.001/((correct_pred[arm]+1)/10)
ZeroDivisionError: float division by zero
                                                                                                                                                        Yours, zq

**Comment by appurwar** [comment]
Hey,
Seems your dataset uses '-1' to denote negative data samples. 
You can either denote the negative data samples as '0' and positive as '1', or change line 95, or change equation at line 95 to accomodate negative values for data samples.
